
# Requires the Bungeecord plugin dependency.
bungeecord: false

# Disable if there is a compatibilty issue or you don't want tab, above head prefixes.
scoreboard: true

# List of Database names are on the resource page, it is case sensitive.
database: "Redis"

# Fill the following info, if you are not using Yaml or Json.
host: "127.0.0.1"

password: ""

timeout: 2000

port: 6379







